# ============================================
# $Id: Makefile,v 1.1 2008/12/15 10:06:51 marc Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
